name: Farms
main: ifteam\Farms\Farms
version: 1.2-alpha
author: ifteam
editer: Roxtigger
api: [3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.1, 3.0.7, 4.0.0]

permissions:
 Farms:
  default: true
 Farms.VIP:
  default: OP
